# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["oss@fastly.com"]
description = "Implements fanout handlers for Websockets, SSE, etc."
language = "go"
manifest_version = 3
name = "Fanout golang starter kit"

[local_server.pushpin]
enable = true

[local_server.backends]
[local_server.backends.origin]
url = "https://example.com/"
override_host = "example.com"

[local_server.backends.self]
url = "http://localhost:7676/"
override_host = "localhost:7676"

[scripts]
build = "go build -o bin/main.wasm ."
env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
post_init = "go get github.com/fastly/compute-sdk-go@latest"
